// Builds the Accessibility Menu widget into public/a11y/widget.v{N}.js
// Run from the repo root: `npm run build:a11y`
import { build, context } from 'esbuild'
import { readFileSync, statSync, writeFileSync, existsSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { gzipSync } from 'node:zlib'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '../..')

// Single source of truth for the version lives in lib/accessibility/version.ts
const versionSrc = readFileSync(resolve(root, 'lib/accessibility/version.ts'), 'utf8')
const version = Number(/A11Y_WIDGET_VERSION\s*=\s*(\d+)/.exec(versionSrc)?.[1])
if (!Number.isInteger(version)) throw new Error('Could not read A11Y_WIDGET_VERSION')

const outfile = resolve(root, `public/a11y/widget.v${version}.js`)
const BUDGET_GZIP_BYTES = 25 * 1024

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints: [resolve(here, 'src/boot.ts')],
  bundle: true,
  format: 'iife',
  target: ['es2018', 'safari13'],
  minify: true,
  sourcemap: true,
  legalComments: 'none',
  outfile,
  define: { __A11Y_VERSION__: String(version) },
  loader: { '.css': 'text' },
  banner: { js: `/* cookie-banner.ca Accessibility Menu v${version} — https://www.cookie-banner.ca */` },
}

/**
 * The bundle is served `immutable, max-age=1y`, so its URL must change whenever
 * its bytes do. banner.js / the head-code snippet append `?b=<hash>` from this
 * generated module — no manual version bump needed for fixes.
 */
function writeBuildHash() {
  const hash = createHash('sha256').update(readFileSync(outfile)).digest('hex').slice(0, 10)
  const target = resolve(root, 'lib/accessibility/build-hash.ts')
  const next = `// Generated by packages/a11y-widget/build.mjs — do not edit.\nexport const A11Y_WIDGET_BUILD = '${hash}'\n`
  if (!existsSync(target) || readFileSync(target, 'utf8') !== next) writeFileSync(target, next)
  return hash
}

function report() {
  const raw = statSync(outfile).size
  const gz = gzipSync(readFileSync(outfile)).length
  const hash = writeBuildHash()
  const ok = gz <= BUDGET_GZIP_BYTES
  console.log(`a11y widget v${version} (${hash}): ${(raw / 1024).toFixed(1)} KB raw, ${(gz / 1024).toFixed(1)} KB gzip ${ok ? 'OK' : 'OVER BUDGET'} (budget ${BUDGET_GZIP_BYTES / 1024} KB)`)
  if (!ok && !process.argv.includes('--watch')) process.exit(1)
}

if (process.argv.includes('--watch')) {
  const ctx = await context({ ...options, plugins: [{ name: 'report', setup(b) { b.onEnd(report) } }] })
  await ctx.watch()
  console.log('watching…')
} else {
  await build(options)
  report()
}
